name: rhub (additional CRAN checks - 01)

on:
  workflow_run:
    workflows: [ "Source Code" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - name: atlas
            image: ghcr.io/r-hub/containers/atlas:latest
          - name: c23
            image: ghcr.io/r-hub/containers/c23:latest
          - name: clang-asan
            image: ghcr.io/r-hub/containers/clang-asan:latest
          - name: clang16
            image: ghcr.io/r-hub/containers/clang16:latest
          - name: clang17
            image: ghcr.io/r-hub/containers/clang17:latest
          - name: clang18
            image: ghcr.io/r-hub/containers/clang18:latest
          - name: clang19
            image: ghcr.io/r-hub/containers/clang19:latest
          - name: clang20
            image: ghcr.io/r-hub/containers/clang20:latest
    name: ${{ matrix.container.name }}
    container:
      image: ${{ matrix.container.image }}
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v5
        with:
          ref: 'src'

      - name: Install dependencies
        run: |
          R -q -e 'if (!require("pak")) install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
          R -q -e 'pak::pkg_install(c("deps::.", "any::rcmdcheck"), dependencies = TRUE)'

      - name: R-CMD-check
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
